name: "Mera pehla workflow"

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
      - 'hotfix/**'
      
jobs: 
  terraforminit: 
     name: init
     runs-on: aadi-bhai
     steps: 
     - name: first run init
       run: echo aadi bhai

      
